#baseURL = "https://mcnair.github.io/CoopVPN/"
baseURL = "https://kwadronaut.github.io/CoOpVPN/"
title = "CoOpVPN"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

relativeURLs = true
canonifyURLs = false

[params]
  description = "A VPN you can trust."
  github_repo = "https://mcnair.github.io/"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
  [languages.es]
    languageName = "Español"
    contentDir = "content/es"
    weight = 2






