baseURL = "https://mcnair.github.io/CoopVPN/"
#baseURL = "https://coopvpn.net/"
title = "CoopVPN"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

#relativeURLs = true
relativeURLs = false
canonifyURLs = false

[params]
  description = "A VPN you can trust."
  github_repo = "https://coopvpn.net/"
  show_homepage_banner = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
  [languages.es]
    languageName = "Español"
    contentDir = "content/es"
    weight = 2
